
  <!--------    HERE     -->
  <div class="ui vertical stripe segment" id="business">
	  <div class="ui middle aligned stackable grid container">
	  	<div class="row customrow business-heading" style="position: relative; overflow: hidden;">
	  		<div class="graysquare" style="
			    position: absolute;
			    width: 150%;
			    height: 100%;
			    background: #f9f9f9;
			    left: -25%;
			    top: 0px;
			"></div>
			<div class="sixteen wide column" style="margin-top: 0px;">
				<h1 class="ui header blue" style="font-family: 'Century Gothic' !important; font-size: 34px;" >Business <b>Solutions</b></h1>
				<h3 style="text-transform: uppercase; font-family: Lato !important; padding-bottom: 10px !important; color: #0084FF; font-size: 24px;">We Provide Small & Medium Business IT Solutions</h3>
				<!-- style="position: relative; height: 40%;" -->

				<!-- position: absolute; bottom: -20%; -->
				<p style="font-size: 15px; text-align: left; ">Computer Repair Geekz is a valued resource for Small Businesses, Professional firms and Practices. We bring a new level of Professionalism to Maryland, DC & Virginia’s IT industry, providing secure Computer networks that are reliable by design and responsive technical support. Whether you are setting up new systems or modifying existing one’s, we provide the expertise you need to get the “job done right, the first time”. From simple desktop and server support, to advanced network and security management. We have the right people for the job. We offer a wide range of services to our commercial clients.</p>
			</div>
			<div class="three wide column link" href="#rm">
				<center>
					<div>
						<i class="icon Fork huge" ></i>
					</div>
					<h5>Remote<br>Monitoring</h5>
				</center>
			</div>
			<div class="three wide column link" href="#ns" >
				<center>
					<div>
						<i class="icon Sitemap huge" ></i>
					</div>
					<h5>Network<br>Setup</h5>
				</center>
			</div>
			<div class="four wide column link" href="#scis" >
				<center>
					<div>
						<i class="icon record huge" ></i>
					</div>
					<h5>Surveillance Cameras <br>Installation & Setup</h5>
				</center>
			</div>
			<div class="three wide column link" href="#ss" >
				<center>
					<div>
						<i class="icon server huge" ></i>
					</div>
					<h5>Server<br>Support</h5>
				</center>
			</div>
			<div class="three wide column link" href="#ws" >
				<center>
					<div>
						<i class="icon wifi huge" ></i>
					</div>
					<h5>Wi-Fi<br>Setup</h5>
				</center>
			</div>

			
			<script type="text/javascript">
				if($(window).width() > 766 ) {
					$('.business-heading').css('height', ($(window).innerHeight() - 117) + 'px');
				}
			</script>

		</div>
		<div class="row customrow">

		  <div class="six wide column" >
			<div class="ui sidemenu" >
		      <div class="ui vertical following fluid accordion text menu">
		      	<div class="item" style="margin-top: 0px">
		      		<h3 class="active title" ><b>Business <b>Solutions</b></b>
		      			<a class="smenu" style="display: none">
				    		<img style="width: 100%; padding: 5px; height: 100%;" src="semantic/dist/images/mobile-menu.png">
				    	</a>
		      		</h3>
		      		<div class="active content menu">
		      			<a class="item active" href="#rm"><i class="angle right icon"></i>Remote Monitoring</a>
		      			<a class="item" href="#ns"><i class="angle right icon"></i>Network Setup</a>
		      			<a class="item" href="#scis"><i class="angle right icon"></i>Surveillance Cameras <br>Installation & Setup</a>
		      			<a class="item" href="#ss"><i class="angle right icon"></i>Server Support</a>
		      			<a class="item" href="#ws"><i class="angle right icon"></i>Wi-Fi Setup</a>

		      		</div>
		      	</div>
		      </div>
		    </div>
		  </div>

		  <div class="ten wide column bus-container">
			<!-- <h1 class="ui header blue"><b>We Provide Small & Medium Business IT Solutions</b></h1>
			<p>Computer Repair Geekz is a valued resource for: Small Businesses, Professional firms and Practices. We bring a new level of Professionalism to DC, Maryland & Virginia IT industry, providing secure Computer networks that are reliable by design and responsive technical support. Whether you are setting up new systems or modifying existing systems, we provide the expertise you need to get the job done right the first time. From simple desktop and server support, to advanced network and security management. We have the right people for the job. We offer a wide range of services to our commercial clients.</p>

			<ul>
				<li>Monthly Support</li>
				<li>Surveillance Camera Setup </li>
				<li>Remote Surveillance Setup</li>
				<li>LAN Networking</li>
				<li>Network Management</li>
				<li>Network Support</li>
				<li>Backup Consulting</li>
				<li>Desktop Support</li>
				<li>Server Support</li>
				<li>System Monitoring</li>
				<li>Microsoft Windows Network Support</li>
				<li>Traffic monitoring</li>
				<li>VPN Setup and Management</li>
				<li>Firewall Setup and Management</li>
				<li>Network monitoring </li>
			</ul> -->

			<div class="content-item rm active">
				<h2 class="ui header blue" id="rm"><b>Remote Monitoring</b></h2>

				<p>Has your company personnel ever complained about the following scenarios?
				<i>"Our Exchange server is acting strange and seems to be slowing down the entire network and all workstations!"</i>
				<i>"The e-mail memo I sent regarding this week’s meeting never reached the entire marketing department!"</i>
				<i>"Our Windows 8.1 server has not had security updates since 2 months!"</i> <i>"Who is handling it?"</i>
				<i>"Why is EMail attachment not printing?! I thought we just bought this printer last month!"</i></p>

				<p>These are some of the most common problems faced by companies who need support services on their servers! Computer Repair Geekz can do this for you remotely. We monitor and routinely check your server in a timely fashion to keep critical security updates installed. We also check server configurations to keep Intranet communications faultless. We delete unnecessary temp files, caches etc., and we keep server hard drives optimal and defragmented to deliver applications faster.</p>

				<p>Here are some of the things that our Company can help your Organization with:
				</p>

				<ul>
					<li>Regular Virus, Malware and Spyware Scans and Eradication</li>
					<li>Ensure Core data backups regularly as well as Server tuning and optimization</li>
					<li>Configure and maintain Server to Workstation settings</li>
					<li>Maintain Email servers and individual Workstations</li>
					<li>Proactive network and system monitoring with active response</li>
					<li>Creation of uniform environments to streamline network management</li>
					<li>Checking internal and Internet Zone security to your server</li>
				</ul>
				<p>Desktops:</p>
				<ul>
					<li>Windows 10, Windows 8 & 8.1, Windows 7, and previous versions Windows Vista & XP.</li>
					<li>HP (Compaq), IBM, Dell, Sony, Gateway, laptops and desktops with Windows.</li>
				</ul>
				<p>Applications:</p>
				<ul>
					<li>Microsoft Office 2003, 2007, 2010, and 2012 (Word, Excel, Access, PowerPoint)</li>
					<li>Microsoft Outlook: group scheduling, shared contracts, and web access</li>
					<li>Business Contact Manager</li>
				</ul>
				<p>Servers:</p>
				<ul>
					<li>Exchange Server 2003, 2008, and 2010</li>
					<li>Small Business Server 2003, 2008, and 2012</li>
					<li>Intranet/Shared platforms</li>
				</ul>
			</div>

			<div class="content-item ns">
				<h2 class="ui header blue" id="ns"><b>Network Setup</b></h2>

				<p>Our highly trained technician will come to your organization, listen to your requirements, take notes about the environment and then deliver a networking solution that is tailored for your company.</p>
				<p>We help with design, setup, maintenance and support for networks and wireless networking solutions, VPN, remote access and creation of uniform environments to streamline network management. Our company understands the diverse range of services and networking variables that are needed. Let us help you figure out in consideration with the size and budget limitations of your company and what is best suited for each kind of set up.</p>

				<p>We can provide the following services for your business network</p>

				<ul>
					<li>Surveillance cameras installation & setup Remote viewing</li>
					<li>Service & Repair for Laptop & Desktop configurations</li>
					<li>Hubs and Switch installation & repair wired routers</li>
					<li>Wireless routers, modems & Wireless Extenders</li>
					<li>Shared networking setup for Printers, scanners & other peripherals</li>
					<li>DSL configuration</li>
					<li>Network Maintenance</li>
					<li>Network Cabling</li>
				</ul>
			</div>

			<div class="content-item scis">
				<h2 class="ui header blue" id="scis"><b>Surveillance Cameras Installation & Setup</b></h2>

				<h2 class="ui header blue" style="font-size: 17px;">About Commercial & Residential Camera Installation</h2>

				<p>Computer Repair Geekz provides complete security camera installations for all commercial and residential properties in Maryland, DC, Virginia and the surrounding areas. State of the art surveillance systems will deter criminal activity and provide an additional level of protection. These advanced surveillance systems are designed to meet complex security challenges with user-friendly interface. Computer Repair Geekz has practical and cost-effective solutions for commercial and residential security needs. Renowned for our outstanding customer service and competitive pricing, we help safeguard what matters most in your life.</p>

				<h2 class="ui header blue" style="font-size: 17px;">FREE Security Analysis That Determines Your Needs</h2>

				<p>A quality security system is an essential part of keeping your home and business safe. Our security professional technician will visit your business, commercial property or residence to perform a thorough security analysis at no cost to you. Each surveillance system, its installation and setup is tailored to our client’s needs, while keeping their budget in mind. At the completion of our analysis, we will recommend a customized commercial or residential security package that meets your requirements and financial constraints. Tighten up the security and decrease theft with surveillance cameras which are designed to target on required areas.</p>

				<ul>
					<li><b>High definition Internet Protocol (POE) cameras</b> – Each camera (2,3,4,6,10 or 12 MP) operates with High Definition Internet Protocol technology (Power Over Ethernet), allowing you to see distinguishing features in real good 1080 Pixels HD quality, 360° coverage, 3x-12x zoom, license plate recognition and detailed imagery. Infrared technology ensures a clear and colored night vision footage.</li>
					<li><b>DVR-Recording device(s)</b> – Preserves high-quality video for playback on a digital format for at least one month of data storage capacity.</li>
					<li><b>Discrete cabling</b> – All cables are hidden from view, keeping your property neat and free of safety hazards. Our expert installers will provide a clean and professional installation.</li>
					<li><b>Remote access to surveillance system</b> – Login to your system via secure remote connection to view your cameras from anywhere in the world using your iPhone/Android, iPad, Laptop or from any computer with an active internet connection.</li>
					<li><b>Retrofitting or replacement</b> – Retrofit older analog-based systems with TVI and high definition Internet Protocol technology along with high resolution HD cameras.</li>
				</ul>

				<center><p style="color: #0084FF; font-size: 20px; padding: 10px;">CALL US TODAY  <b style="font-size: 24px">443.535.1483</b>  TO GET FREE SECURITY EVALUATION ANALYSIS FOR YOUR BUSINESS AND/OR RESIDENCE</p></center>

			</div>

			<div class="content-item ss">
				<h2 class="ui header blue" id="ss"><b>Server Support</b></h2>

				<div><b>Desktop Support</b></div>
				<p>Email and printer configuration. Network and peripheral communication. Tuning the PC for maximum performance.</p>

				<div><b>Application Support</b></div>
				<p>Installation, updates, license management, hands-on training, or configuration.</p>

				<div><b>Server Administration</b></div>
				<p>We can perform Operating System rollouts, file, email and print server management for your company. We deal securely with user permissions and file security. We backup systems and provide storage of critical company data. We perform installation of all important updates, patches, virus protection, spyware and malware protection, either On-Site or Remotely.</p>
			</div>

			<div class="content-item ws">
				<h2 class="ui header blue" id="ws"><b>Wi-Fi Setup</b></h2>

				<p>WIRELESS is FUTURE</p>
				<p>Discover the freedom without cables</p>
				<p>We can help your company setup a wireless network in no time, giving you cable-free capabilities for</p>
				<ul>
					<li>DSL or cable coordination</li>
					<li>Multi-user Internet access</li>
					<li>Printer, scanner and other peripheral sharing</li>
					<li>Cable free data and application access</li>
				</ul>
				<p>Wireless Networking Installation</p>
				<ul>
					<li>Set up and connect a wireless router</li>
					<li>Connect an additional wireless or wired print server</li>
					<li>Connect and configure: laptops, desktops, media devices, and media center extenders</li>
					<li>Configure and demonstrate file sharing across the wireless network</li>
					<li>Eradicate General network issues that you may currently have</li>
				</ul>
			</div>

		  </div>

		  
		  <script type="text/javascript">

		  	$(window).scroll(function() {
	    		if($(window).scrollTop() > $(window).innerHeight() - 80){
	    			$('.sidemenu').addClass('fixed');
	    		} else {
	    			$('.sidemenu').removeClass('fixed');
	    		}

	    		if($(window).scrollTop() > ($(document).height() * 3 / 4)) {
	    			$('.sidemenu').removeClass('fixed');
	    		}
	    	});
		  	// $('.business-heading .link').click(function(e) {
	    	// 	e.preventDefault();
	    	// 	e.stopPropagation();
	    	// 	self = $(this);
	    	// 	$('html, body').animate({ scrollTop : ($(self.attr('href')).offset().top - 135) }, 500, "swing");
	    	// });

		   //  	var lastindex = 1;
		   //  	$('.sidemenu a, .business-heading .link').click(function(e) {
		   //  		e.preventDefault();
		   //  		e.stopPropagation();
		   //  		var self = $(this);

		   //  		$('#container').animate({ opacity:0 }, 400, function() {
		   //  			$('html, body').animate({ scrollTop : ($(self.attr('href')).offset().top - 135) }, Math.abs(lastindex-self.index())*100 + 500, "easeOutCubic");
					// 	$(this).animate({ opacity:1 }, 500);
					// });
		    		
		   //  		lastindex = self.index();
		   //  	});

			var lastindex = 1;
	    	$('.sidemenu .active.content.menu a, .business-heading .link').click(function(e) {
	    		e.preventDefault();
		   		e.stopPropagation();
	    		var self = $(this);

	    		$('.sidemenu a').removeClass('active');
	    		$('.sidemenu a[href=' + self.attr('href') + ']').addClass('active');

	    		if ($(window).width() < 766) $('.smenu.open').trigger('click');

	    		$('.bus-container').animate({ opacity:0 }, 400, function() {
		    		$('.bus-container .content-item').removeClass('active');
		    		$('.bus-container .content-item' + self.attr('href').replace('#', '.')).addClass('active');

		    		$('html, body').animate({ scrollTop : ($('.bus-container').offset().top - 160) }, Math.abs(lastindex-self.index())*100 + 500, "easeOutCubic");
		    		$(this).animate({ opacity:1 }, 500);
		    		$(".srv-container").mCustomScrollbar("scrollTo", 'top');
		    	});

		    	lastindex = self.index();
	    	});

	    	$('.smenu').click(function(e) {
				e.preventDefault();
				e.stopPropagation();
				if($(this).hasClass('open')) {
					$('.sidemenu .content.menu').slideUp(100);
				} else {
					$('.sidemenu .content.menu').slideDown(200);
				}

				$(this).toggleClass('open');
			});


			if($(window).width() > 766 ) {
	    		$('.bus-container').css({overflow : 'auto', height : $(window).innerHeight() - 240 + 'px', minHeight: $(window).innerHeight() - 240 + 'px', paddingRight : '20px'});

		    	$(".bus-container").mCustomScrollbar({
				    theme:"dark",
					scrollInertia: 100
				});
			}
		  </script>

		</div>
	  </div>
	</div>
