
  <div id="services" class="ui vertical stripe segment" >
  <div class="ui middle aligned stackable grid container">
    <div class="row customrow services-heading" style="position: relative; overflow: hidden;">
      <div class="graysquare" style="
          position: absolute;
          width: 150%;
          height: 100%;
          background: #f9f9f9;
          left: -25%;
          top: 0px;
      "></div>
      <div class="sixteen wide column" style="margin-top: 0px;">
        <h1 class="ui header blue" style="font-family: 'Century Gothic' !important; font-size: 34px; ">Our <b>Services</b></h1>
      </div>
      <div class="four wide column link" href="#vasr">
        <center>
          <div>
            <i class="icon bug huge" ></i>
          </div>
          <h5>Virus & Spyware<br>Removal</h5>
        </center>
      </div>
      <div class="four wide column link" href="#drb" >
        <center>
          <div>
            <i class="icon server huge" ></i>
          </div>
          <h5>Data Recovery<br>& Backup</h5>
        </center>
      </div>
      <div class="four wide column link" href="#lnaprs" >
        <center>
          <div>
            <i class="icon laptop huge" ></i>
          </div>
          <h5>Pc, Mac, Laptop<br>& Notebook Repairs</h5>
        </center>
      </div>
      <div class="four wide column link" href="#wns" >
        <center>
          <div>
            <i class="icon wifi huge" ></i>
          </div>
          <h5>Wi-Fi Networking<br>& Security</h5>
        </center>
      </div>
      <div class="sixteen wide column gap" style="margin-top: 25px"></div>
      <div class="four wide column link" href="#ncs" >
        <center>
          <div>
            <i class="icon computer huge" ></i>
          </div>
          <h5>New Computer<br>Setup</h5>
        </center>
      </div>
      <div class="four wide column link" href="#pct" >
        <center>
          <div>
            <i class="icon travel huge" ></i>
          </div>
          <h5>Personal Computer Training</h5>
        </center>
      </div>
      <div class="four wide column link" href="#susc" >
        <center>
          <div>
            <i class="icon lightning huge" ></i>
          </div>
          <h5>Maximize PC Speed<br>& Performance</h5>
        </center>
      </div>
      <div class="four wide column link" href="#iimr" >
        <center>
          <div>
            <i class="icon tablet huge" ></i>
          </div>
          <h5>iPhone, iPod<br>& iPad Repair</h5>
        </center>
      </div>

      <script type="text/javascript">
        
        if($(window).width() > 766 ) {
          $('.services-heading').css('height', ($(window).innerHeight() - 117) + 'px');
        }
      </script>

    </div>
    <div class="row customrow" style="">
      <div class="six wide column" >
        <div class="ui sidemenu" >
            <div class="ui vertical following fluid accordion text menu">
              <div class="item" style="margin-top: 0px">
                <h3 class="active title" ><b>Our <b>Services</b></b>
                  <a class="smenu" style="display: none">
                  <img style="width: 100%; padding: 5px; height: 100%;" src="semantic/dist/images/mobile-menu.png">
                </a>
            </h3>
                <div class="active content menu">
                  <a class="item active" href="#vasr"><i class="angle right icon"></i>Virus & Spyware Removal</a>
                  <a class="item" href="#drb"><i class="angle right icon"></i>Data Recovery & Backup</a>
                  <a class="item" href="#lnaprs"><i class="angle right icon"></i>Pc, Mac, Laptop & Notebook Repairs</a>
                  <a class="item" href="#wns"><i class="angle right icon"></i>Wi-Fi Networking & Security</a>
                  <a class="item" href="#ncs"><i class="angle right icon"></i>New Computer Setup</a>
                  <a class="item" href="#pct"><i class="angle right icon"></i>Personal Computer Training</a>
                  <a class="item" href="#susc"><i class="angle right icon"></i>Maximize PC Speed & Performance</a>
                  <a class="item" href="#iimr"><i class="angle right icon"></i>iPhone, iPod & iPad Repair</a>
                  
                  <!-- <a class="item" href="#crus">Computer Repairs & Upgrade Services</a> -->
                  <a class="item" href="#cns"><i class="angle right icon"></i>Computer Networking & Security</a>
                  <a class="item" href="#wnt"><i class="angle right icon"></i>Wireless Network Troubleshooting</a>
                  <!-- <a class="item" href="#cts">Computer Troubleshooting Services</a> -->
                  <a class="item" href="#cioaro"><i class="angle right icon"></i>Install or Reinstall Operating System</a>
                  <!-- <a class="item" href="#amcr">Apple MAC Computer Repair</a> -->
                  <a class="item" href="#icr"><i class="angle right icon"></i>Internet Configuration Repair</a>
                  <a class="item" href="#oss"><i class="angle right icon"></i>Remote Support</a>
                </div>
              </div>
            </div>
          </div>
      </div>

      <div class="ten wide column srv-container" >
        <div class="content-item vasr active">
          <h3 class="ui header blue" id="vasr"><b>Virus & Spyware Removal</b></h3>
          <p>Is your computer <b>RUNNING SLOWER</b>than normal?</p>

          <p>Do you see unusual <b>POP-UPS</b> & <b>STRANGE ICONS</b>?</p>

          <p>Does your <b>PROGRAMS</b> or <b>APPS</b> shutdown <b>RANDOMLY</b>?</p>

          <p><b>Your Computer might be HEAVILY INFECTED and not Performing at its Optimal Speed!!</b> But do not worry as this is a very common problem. We receive similar complaints daily and our expert techs have a great experience in executing virus and spyware removal from your PC. It will also maximize your computer’s speed and performance. We include a full tune-up and servicing of your Operating System within our virus and spyware removal procedure. The spywares and viruses are sometimes so deeply entrenched within your hard-drive and boot-memory records that it almost becomes impossible to remove them without an Expert’s help and specialized software. This is where our Expert Techs will come in and perform the required services.</p>
          
          <h4><b>OUR EXPERT GEEK TECH WILL:</b></h4>

          <ul>
            <li>CleanUp the Hard Drive</li>
            <li>Clean Memory & Boot Records</li>
            <li>Clean the Interior using Compressed Air</li>
            <li>Fine-Tune the Operating System</li>
            <li>Install Critical Security Updates to prevent future outbreaks</li>
            <li>Install Adware blockers & Anti-Virus Software</li>
            <li>Disable unnecessary Applications from running in the background</li>
            <li>Firmware Updates</li>
            <li>Disk CleanUp & Defragmentation</li>
          </ul>
          <center><p style="color: #0084FF; font-size: 20px; padding: 10px;">"Computer Repair Geekz should be your first and last Stop in case of a breakdown or crucial computer emergency"</p></center>
        </div>
        <div class="content-item drb">
          <h3 class="ui header blue" id="drb"><b>Data Recovery & Backup</b></h3>

          <p>Did you lose your data accidentally or due to hardware/software issues? Do not worry! Our Technicians will carefully recover your data onto an external storage device such as DVD, CD or USB drive. We can even transfer some or all of your data for backup to prevent loss of any valuable digital information. Your costs would depend on the complexity of the data and amount of files to be recovered. Our technicians will help you evaluate various backup and storage options and choose the most viable and suitable solution for you</p>
          
          <ul>
            <li>CD/DVD backup</li>
            <li>Flash drives</li>
            <li>External hard drives</li>
            <li>Hard Drive Recovery</li>
            <li>Desktop / Laptop Recovery</li>
            <li>File Recovery</li>
            <li>Digital Photo Recovery</li>
            <li>RAID configurations</li>
            <li>Third party Off-Site backup solutions</li>
          </ul>
        </div>
        <div class="content-item lnaprs">
          <h3 class="ui header blue" id="lnaprs"><b>Pc, Mac, Laptop & Notebook Repairs</b></h3>

          <p>Let our trained specialists repair any and every problem with your Dell, Apple, Hewlett Packard, Compaq, Sony, Gateway, Toshiba, Acer, Samsung, Asus, iMac, MacBook or custom built systems. Be it a laptop or a desktop, we can take good care of the system beginning with a FREE diagnostics! If there are parts that need to be replaced or repaired, we can get them from our vendors the same day, so you are up and running in the quickest time possible.  <b style="color: #0084FF; font-size: 12pt;">“We Treat YOUR Machine As Our OWN”</b></p>

          <ul>
            <li>LCD repairs</li>
            <li>Video Chip Repair</li>
            <li>Power Jack replacement</li>
            <li>No Internet – Page Cannot Be Displayed</li>
            <li>Boot up problems</li>
            <li>Blue Screen errors</li>
            <li>Peripherals errors</li>
            <li>Hardware failures</li>
            <li>Motherboard repairs</li>
            <li>Motherboard replacement</li>
            <li>Processor replacement</li>
            <li>Memory upgrades</li>
            <li>Custom built PC/ gaming machine</li>
          </ul>
          <!-- <p><b>Computer Repair Geekz should be your first and last Stop in case of a breakdown or crucial computer emergency!</b></p>

          <p>We also service apple macintosh computers and laptops. Including iMacs, iBooks, macbooks, mac minis, and all other types of apple macintosh computers. We can help you with software and hardware issues including operating system install, operating system upgrades, macs that don't boot up, macs that require lcd replacement, etc. </p> -->
        </div>
        <div class="content-item wns">
          <h3 class="ui header blue" id="wns"><b>Wi-Fi Networking & Security</b></h3>

          <p>Do you need a wireless network set up in your home or business? Do you need help choosing a new modem, router, or network switch? Let us take out all the guesswork by setting up your internet and wireless network connections. And by providing the support you need when you have problems with your internet or network. Linksys and Netgear allowed wireless networking to emerge as the leading technology for building state-of-the-art computer networks and reliable products. We can help you setup a wireless network in no time, giving you cable-free capabilities for</p>

          <ul>
            <li>Multi-user Internet Access</li>
            <li>Printer, Scanner and other Peripheral Sharing</li>
            <li>Cable Free Data and Application Access</li>
            <li>We can set up, configure, and secure your wireless and wired networks.</li>
            <li>Secure your broadband signal from attacks.</li>
            <li>Install and configure your network devices such as laptops, gaming consoles, and smartphones.</li>
            <li>Setup a VOIP(Voice Over IP) connection.</li>
            <li>Help you to share your files with other computers on your network if you wish.</li>
            <li>Repair network and internet connectivity.</li>

          </ul>
        </div>
        <div class="content-item ncs">
          <h3 class="ui header blue" id="ncs" ><b>New Computer Setup</b></h3><p>Buying a new computer can be fun but setting it up is a daunting task. We can come out and help you with everything from unpacking the box to getting your computer up and running. Get you connected to the internet with your e-mail. We can also help transfer data from your old computer to your new one.</p>
        </div>
        <div class="content-item pct">
          <h3 class="ui header blue" id="pct"><b>Personal Computer Training</b></h3><p>It can be frustrating, working on a computer and not knowing what buttons to push. Many of your friends and family seem to be enjoying their computers so much but you are always frustrated. Make a list of things you want to learn or just ask for general computer training and we will send out our expert and courteous tech to help you get better acquainted with your computer and teach you how to get the tasks done!</p>
        </div>
        <div class="content-item susc">
          <h3 class="ui header blue"  id="susc" ><b>Maximize PC Speed & Performance</b></h3><p>Over time computers get slower and slower because they tend to gather junk. We will check your computer's start-up items to ensure it is as clean as possible. We will uninstall any unused computer programs and clear out temporary files. We can remove extra toolbars and widgets that are just slowing down your computer. Finally we will check your computer memory and if needed we will suggest memory upgrades.</p>
        </div>
        <div class="content-item iimr">
          <h3 class="ui header blue" id="iimr" ><b>iPhone, iPod & iPad Repair</b></h3>

          <h2 class="ui header blue" style="font-size: 17px;">Computer Repair Geekz is your one-stop shop for all of your iPhone, iPod & iPad needs!</h2>

          <h4><b>iPad</b></h4>
          <p>We love the iPad. It’s a bit like Apple squeezed everything that was great about the iPhone and the Mac into a convenient, shiny, handheld device!
          There can be some issues with these devices at times. If some of these issues are occurring like <b>backing up and syncing, seemingly random jerky performance,</b> and more. these problem can turn your sleek and simple device into an expensive flying projectile you might later have to retrieve from your neighbour’s yard. We can service all generations of iPad tablets and pride ourselves as being the most honest repair shop around. We offer affordable prices and use nothing but the highest quality parts, we are here to make your life easier!</p>
          <ul>
            <li>Slow Performance</li>
            <li>Broken LCD</li>
            <li>Spyware Removal</li>
            <li>Battery/Charging issues</li>
            <li>Charging ports</li>
            <li>No sound/No microphone</li>
            <li>Water Damage</li>
            <li>Backup and Syncing</li>
          </ul>
          <h4><b>iPhone</b></h4>
          <p>Cell phones have become a crucial element of everyday modern life. Their mobility and connectivity have made them enormously useful tools for both personal and business lifestyles. If your iPhone isn’t working, we can probably repair it, instead of buying a new usually saving you hundreds.</p>
          
          <br>
          <h2 class="ui header blue" style="font-size: 17px;  padding: 0px !important;">Common Iphone Repair Solutions</h2>
          <ul>
            <li>iPhone Screen Repair </li>
            <li>Touch Screen/LCD Replacement</li>
            <li>Back Cover Replacement</li>
            <li>Dock Connector/Microphone Replacement</li>
            <li>Battery Replacement</li>
            <li>Camera Replacement</li>
            <li>Home Button Replacement</li>
            <li>Earpiece Replacement</li>
            <li>Water Damage</li>
          </ul>
        </div>
        <div class="content-item crus">
          <h3 class="ui header blue" id="crus" ><b>Computer Repairs & Upgrade Services</b></h3><p>If your computer just won't boot or you have a broken LCD screen, our computers repairs and upgrades are just what your looking for. We can help you determine which parts are bad, order replacements or suggest upgrades, and install them in your computer properly. We can also assist with operating system or software upgrades and ensure you have the appropriate hardware to do so. 
        </p>
        </div>
        <div class="content-item cns">
          <h3 class="ui header blue" id="cns"><b>Computer Networking & Security</b></h3><p>Ensuring your network is up and running securely is very important and we can help you with it. We can make sure each computer is connected properly and has access to all the network resources. We can add  and configure additional connections. Also we can make sure your network resources are secure and only authorized users have access to it.</p>
        </div>
        <div class="content-item wnt">
          <h3 class="ui header blue" id="wnt"><b>Wireless Network Troubleshooting</b></h3><p>We can troubleshoot your existing wireless network or help you setup a new one. Also we can help you add devices to your existing wireless network. Sometimes the problem just lies with one device like a desktop, laptop, or gaming console, we can isolate the issue and get you back on the internet. We do stock wireless routers and adapters with us in case we need to replace one.</p>
        </div>
        <div class="content-item cts">
          <h3 class="ui header blue" id="cts"><b>Computer Troubleshooting Services</b></h3><p>Troubleshooting encompasses anything that doesn't fit the other categories. We can help you check settings, make adjustments, help with upgrades, find out why you can't do x, or why that message won't go away, etc. All your problems can be solved, just have one of our On-Site techs help you troubleshoot them away. </p>
        </div>
        <div class="content-item cioaro">
          <h3 class="ui header blue" id="cioaro"><b>Install or Reinstall Operating System</b></h3><p>If your operating system is acting up and you have tried everything, sometimes the best remedy is to start fresh. We can help you start over with a fresh install of your operating system. We will also ensure that all the proper drivers are loaded so all your devices work, such as printer, sound, video, ethernet, etc. We can also help you reinstall the software your computer had before. We also do help in upgrading your operating system.</p>
        </div>
        <div class="content-item amcr">
          <h3 class="ui header blue" id="amcr"><b>Apple MAC Computer Repair</b></h3><p>We also service apple macintosh computers and laptops. Including iMacs, iBooks, macbooks, mac minis, and all other types of apple macintosh computers. We can help you with software and hardware issues including operating system install, operating system upgrades, macs that don't boot up, macs that require lcd replacement, etc. </p>
        </div>
        <div class="content-item icr">
          <h3 class="ui header blue" id="icr"><b>Internet Configuration Repair</b></h3><p>We can troubleshoot your existing dial-up or broadband internet connection and/or help you configure a new one. Also we can help you setup for share the connection with multiple computers and/or devices using a router.</p>
        </div>
        <div class="content-item oss">
          <h3 class="ui header blue" id="oss"><b>Remote Support</b></h3>
          <p>In today’s fast-paced world, experiencing downtime from your computer or IT network can lead to loss of work, productivity, and revenue, something no company wants or can afford to experience. In a world where almost all business relies on properly functioning computers, networks, servers, and other IT equipment, receiving reliable, efficient, and cost effective technical support is vital.</p>
          <p>At Computer Repair Geekz we offer remote technical support, meaning we can help resolve almost any computer issue via remote tech support. These include:</p>
          <ul>
            <li>Virus removal</li>
            <li>Scanning for spyware</li>
            <li>Driver installation</li>
            <li>Software installation</li>
            <li>Software upgrades</li>
            <li>Some hardware diagnosis</li>
            <li>And more!</li>
          </ul>

          <h2 class="ui header blue" style="font-size: 17px;">How Does It Work?</h2>
          <p>There are many ways an IT specialist can provide remote support. The most important factor to consider is a reliable Internet connection. When we provide assistance to business owners and managers, we can connect to your computer and see exactly what you see as if we were sitting right next to you! Our remote support is performed over a secure connection, and we always ask for permission to see and access your computer during each support session. This allows us to quickly see and resolve the problem without wasting any time.</p>

          <p> <b>If seeking remote technical support on an as-needed basis, our assistance is available at $50.00 per hour (one hour minimum charge required).</b> </p>

          <h2 class="ui header blue" style="font-size: 17px; ">Benefits of Remote Technical Support</h2>
          <p><b>Time efficient</b> – Instead of calling an IT company to come inspect your computer or traveling to a tech support specialist, remote technical support eliminates the need for travel. <b>We can connect to your computer from anywhere at any time</b>. You’ll receive technical support from an industry expert almost instantly. You can also reduce time spent traveling, which means more time is spent working!</p>

          <p><b>Cost effective</b> – Eliminate travel expenditures (such as gas) and don’t waste company money on bringing an IT professional into your place of business, which could result in expensive fees from hourly wages, depending on the severity of your issue.</p>

          <p><b>Reliable</b> – When you receive remote assistance from a certified IT professional, like Maryland Computer Service, you can rest assured your issue will be resolved in a timely manner. We are a Microsoft Certified Partner and Microsoft Small Business Specialist, so we know just what it takes to resolve your problems and get your business back online as quickly as possible.</p>

        </div>
      </div> 
      

      <script type="text/javascript">
        
        

          $(window).scroll(function() {
            if($(window).scrollTop() > $(window).innerHeight() - 80){
              $('.sidemenu').addClass('fixed');
            } else {
              $('.sidemenu').removeClass('fixed');
            }

            if($('.bottomgray').offset().top < $(window).innerHeight() + $(window).scrollTop() - 30) {
              $('.sidemenu').addClass('bottom');
            } else {
              $('.sidemenu').removeClass('bottom');
            }
          });

          // $('.sidemenu a, .services-heading .link').click(function(e) {
          //  e.preventDefault();
          //  e.stopPropagation();
          //  self = $(this);
          //  $('html, body').animate({ scrollTop : ($(self.attr('href')).offset().top - 135) }, 500, "swing");
          // });

         

         //   var lastindex = 1;
         //   $('.sidemenu a, .services-heading .link').click(function(e) {
         //     e.preventDefault();
         //     e.stopPropagation();
         //     var self = $(this);

         //     $('#container').animate({ opacity:0 }, 400, function() {
            //  $('html, body').animate({ scrollTop : ($(self.attr('href')).offset().top - 135) }, Math.abs(lastindex-self.index())*100 + 500, "easeOutCubic");
            //  $(this).animate({ opacity:1 }, 500);
            // });

         //     lastindex = self.index();
         //   });

        var lastindex = 1;
          $('.sidemenu .active.content.menu a, .services-heading .link').click(function(e) {
            e.preventDefault();
            e.stopPropagation();
            var self = $(this);



            $('.sidemenu a').removeClass('active');
            $('.sidemenu a[href=' + self.attr('href') + ']').addClass('active');
            if ($(window).width() < 766) $('.smenu.open').trigger('click');
            $('.srv-container').animate({ opacity:0 }, 400, function() {
              $('.srv-container .content-item').removeClass('active');
              $('.srv-container .content-item' + self.attr('href').replace('#', '.')).addClass('active');

              $('html, body').animate({ scrollTop : ($(".srv-container").offset().top - 160) }, Math.abs(lastindex-self.index())*100 + 500, "easeOutCubic");
              $(this).animate({ opacity:1 }, 500);
              $(".srv-container").mCustomScrollbar("scrollTo", 'top');
            });

            lastindex = self.index();
          });

          $('.smenu').click(function(e) {
          e.preventDefault();
          e.stopPropagation();
          if($(this).hasClass('open')) {
            $('.sidemenu .content.menu').slideUp(100);
          } else {
            $('.sidemenu .content.menu').slideDown(200);
          }

          $(this).toggleClass('open');
        });

          if($(window).width() > 766 ) {
            $('.srv-container').css({overflow : 'auto', height : $('.sidemenu').height() - 10 + 'px', minHeight: $('.sidemenu').height() - 10 + 'px', paddingRight : '20px'});

            $(".srv-container").mCustomScrollbar({
              theme:"dark",
              scrollInertia: 100
          });
        }
        </script>
    </div>
  </div>
</div>
